fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.12.0"
    sysctl:
      repo: "https://github.com/thias/puppet-sysctl.git"
      ref: "1.0.6"
  symlinks:
    ucarp: "#{source_dir}"
