---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 2.1.0
script: bundle exec rake spec
env:
  - PUPPET_VERSION="~> 4.0.0"
matrix:
  include:
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 4.0.0"
