#!/bin/bash
# File managed by puppet
UCARP=/usr/sbin/ucarp
EXTRA_PARAMS="-x $IF_ALIAS"
UCARP_LOG_TAG="ucarp-script"
PID_FILE="/run/ucarp.$IF_UCARP_VIP.pid"

if [ ! -x $UCARP ]; then
    exit 0
fi

if [ -z "$IF_UCARP_UPSCRIPT" ]; then
    IF_UCARP_UPSCRIPT=/usr/share/ucarp/vip-up
fi

if [ -z "$IF_UCARP_DOWNSCRIPT" ]; then
    IF_UCARP_DOWNSCRIPT=/usr/share/ucarp/vip-down
fi

if [ -n "$IF_UCARP_MASTER" ]; then
    if ! expr "$IF_UCARP_MASTER" : "no\|off\|false\|0" > /dev/null; then
        EXTRA_PARAMS="$EXTRA_PARAMS -P"
    fi
fi

if [ -n "$IF_UCARP_ADVSKEW" ]; then
    EXTRA_PARAMS="$EXTRA_PARAMS -k $IF_UCARP_ADVSKEW"
fi

if [ -n "$IF_UCARP_ADVBASE" ]; then
    EXTRA_PARAMS="$EXTRA_PARAMS -b $IF_UCARP_ADVBASE"
fi

if [ -n "$IF_UCARP_DEADRATIO" ]; then
    EXTRA_PARAMS="$EXTRA_PARAMS -r $IF_UCARP_DEADRATIO"
fi

if [ -n "$IF_UCARP_NOMCAST" ]; then
    if ! expr "$IF_UCARP_NOMCAST" : "no\|off\|false\|0" > /dev/null; then
        EXTRA_PARAMS="$EXTRA_PARAMS -M"
    fi
fi

if [ -n "$IF_UCARP_XPARAM" ]; then
    EXTRA_PARAMS="$EXTRA_PARAMS -x $IF_UCARP_XPARAM"
fi

# Allow logging to custom facility
if [ -n "$IF_UCARP_FACILITY" ] ; then
    EXTRA_PARAMS="$EXTRA_PARAMS -f $IF_UCARP_FACILITY"
fi

if [ "$MODE" == "start" ] ; then
    START_STOP_ARGS="-m -S"
elif [ "$MODE" == "stop" ] ; then
    START_STOP_ARGS="-K"
fi
 
# Modified to use start / stop /daemon SERIOUSLY CHANGE THE FILE
if [ -n "$IF_UCARP_VID" -a -n "$IF_UCARP_VIP" -a -n "$IF_UCARP_PASSWORD" ]; then
    SS_CMD="start-stop-daemon $START_STOP_ARGS -p $PID_FILE -x $UCARP -- -B -i $IFACE -s $IF_ADDRESS -z -v $IF_UCARP_VID -p $IF_UCARP_PASSWORD -a $IF_UCARP_VIP -u $IF_UCARP_UPSCRIPT -d $IF_UCARP_DOWNSCRIPT $EXTRA_PARAMS"
    echo "Starting or stopping ucarp, command: $SS_CMD" | /usr/bin/logger -t $UCARP_LOG_TAG
    $SS_CMD | /usr/bin/logger -t $UCARP_LOG_TAG 2>&1
    echo "ucarp/start-stop-daemon returned $?" | /usr/bin/logger -t $UCARP_LOG_TAG
fi

# vi:ai sw=4 ts=4 tw=0 et
